// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4wfd_Cqzi4p-3ww-dxnAftTay6XI2NAw',
    appId: '1:52756953014:web:42c73267000f1f1efdf317',
    messagingSenderId: '52756953014',
    projectId: 'fitnessapp-c0236',
    authDomain: 'fitnessapp-c0236.firebaseapp.com',
    storageBucket: 'fitnessapp-c0236.firebasestorage.app',
    measurementId: 'G-J3ZKPX90SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtXPtcb1BNFZogqfF46U4rm-WfDWfbSpI',
    appId: '1:52756953014:android:7b38439d84e16610fdf317',
    messagingSenderId: '52756953014',
    projectId: 'fitnessapp-c0236',
    storageBucket: 'fitnessapp-c0236.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsiZFuMZpQi1RAyzC7Yz-hccJeDoOUGoo',
    appId: '1:52756953014:ios:0f2af7e6dd2858aefdf317',
    messagingSenderId: '52756953014',
    projectId: 'fitnessapp-c0236',
    storageBucket: 'fitnessapp-c0236.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsiZFuMZpQi1RAyzC7Yz-hccJeDoOUGoo',
    appId: '1:52756953014:ios:0f2af7e6dd2858aefdf317',
    messagingSenderId: '52756953014',
    projectId: 'fitnessapp-c0236',
    storageBucket: 'fitnessapp-c0236.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4wfd_Cqzi4p-3ww-dxnAftTay6XI2NAw',
    appId: '1:52756953014:web:409fe89b010ab96afdf317',
    messagingSenderId: '52756953014',
    projectId: 'fitnessapp-c0236',
    authDomain: 'fitnessapp-c0236.firebaseapp.com',
    storageBucket: 'fitnessapp-c0236.firebasestorage.app',
    measurementId: 'G-7PTNH7EBKB',
  );

}